# Generated by Django 4.1.5 on 2023-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedmodel",
            name="natureza",
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name="parsedmodel",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("debito", "Debito"),
                    ("boleto", "Boleto"),
                    ("financiamento", "Financiamento"),
                    ("credito", "Credito"),
                    ("recebimento emprestimo", "Emprestimo"),
                    ("vendas", "Vendas"),
                    ("recebimento ted", "Ted"),
                    ("recebimento doc", "Doc"),
                    ("aluguel", "Aluguel"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
